tags:
- name: zombie
  description: zombie API
- name: item
  description: item API
- name: rates
  description: rates api

paths:
# [POST] zombie
  /zombie:
    post:
      tags:
      - zombie
      summary: Add zombie
      parameters:
      - name: body
        in: body
        description: zombie Data
        required: true
        schema:
          $ref: '#/definitions/zombie'
      responses:
        201:
          description: 'Created'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# [GET] zombie
  /zombie/list:
    get:
      tags: 
      - zombie
      summary: Get all zombies
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'

# [GET] zombie/total/id
  /zombie/total/{id}:
    get:
      tags: 
      - zombie
      summary: Get total value of all zombie items.
      parameters:
      - name: id
        in: path
        description: zombie Id
        required: true
        type: integer
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'
  
# [GET] zombie/items/id
  /zombie/items/{id}:
    get:
      tags: 
      - zombie
      summary: Get zombie items by id
      parameters:
      - name: id
        in: path
        description: zombie Id
        required: true
        type: integer
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'

# [GET] zombie/id
  /zombie/{id}:
    get:
      tags: 
      - zombie
      summary: Get zombie by id
      parameters:
      - name: id
        in: path
        description: zombie Id
        required: true
        type: integer
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'


# [DELETE] zombie/id
    delete:
      tags:
      - zombie
      summary: Delete zombie by Id
      parameters:
      - name: id
        in: path
        description: zombie Id
        required: true
        type: integer
      responses:
        200:
          description: 'OK'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'
# [PUT] zombie/id
    put:
      tags:
      - zombie
      summary: Update zombie by Id
      parameters:
      - name: id
        in: path
        description: zombie Id
        required: true
        type: integer
      - name: body
        in: body
        description: zombie Data
        required: true
        schema:
          $ref: '#/definitions/zombies'
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# [GET] item
  /item/update:
    get:
      tags: 
      - item
      summary: Update all item prices from external api.
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'

# [GET] item
  /item/list:
    get:
      tags: 
      - item
      summary: Get all items
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'

# [POST] item
  /item:
    post:
      tags:
      - item
      summary: Add item
      parameters:
      - name: body
        in: body
        description: item Data
        required: true
        schema:
          $ref: '#/definitions/item'
      responses:
        201:
          description: 'Created'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

  # [DELETE] item
    delete:
      tags:
      - item
      summary: Add item
      parameters:
      - name: body
        in: body
        description: delete item
        required: true
        schema:
          $ref: '#/definitions/item'
      responses:
        201:
          description: 'Created'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# [GET] rates
  /rates/update:
    get:
      tags: 
      - rates
      summary: Update all rates from external api
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'
          
# [GET] rates
  /rates:
    get:
      tags: 
      - rates
      summary: Get all saved rates.
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'
###################################################################




# definitions
definitions:
  zombie:
    type: object
    required:
        - name
    properties:
      name:
        type: string
        description: zombie name
  item:
    type: object
    required:
        - name
    properties:
      zombieId:
        type: number
        description: zombieId
      itemId:
        type: number
        description: itemId
schemes:
 - https
 - http
